// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TmsApi_Module4_Session1.TmsApi.Data.CompiledModels
{
    public partial class TmsDbContextModel
    {
        private TmsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("903df2df-4172-4739-bae1-99b0e79bd60b"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var assessment = AssessmentEntityType.Create(this);
            var certificate = CertificateEntityType.Create(this);
            var course = CourseEntityType.Create(this);
            var enrollment = EnrollmentEntityType.Create(this);
            var student = StudentEntityType.Create(this);

            AssessmentEntityType.CreateForeignKey1(assessment, course);
            CertificateEntityType.CreateForeignKey1(certificate, course);
            CertificateEntityType.CreateForeignKey2(certificate, student);
            EnrollmentEntityType.CreateForeignKey1(enrollment, course);
            EnrollmentEntityType.CreateForeignKey2(enrollment, student);

            AssessmentEntityType.CreateAnnotations(assessment);
            CertificateEntityType.CreateAnnotations(certificate);
            CourseEntityType.CreateAnnotations(course);
            EnrollmentEntityType.CreateAnnotations(enrollment);
            StudentEntityType.CreateAnnotations(student);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
