// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TmsApi.Data;
using TmsApi_Module4_Session1.TmsApi.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TmsDbContext), typeof(TmsDbContextModel))]
